* What is Imagine?

Imagine is a clean and creative single page theme designed for org mode exports. It currently supports latex, code blocks, lists, and tables.

To see imagine live see:
[[http://jessekelly881-imagine.surge.sh/][Imagine]]


* How to use

To use Imagine copy the imagine.css file into the folder you want to use it and them add the following headers to your org mode document:

#+BEGIN_SRC org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="imagine.css" />
#+OPTIONS: toc:nil num:nil html-style:nil
#+END_SRC

* Syntax highlighting
Getting the syntax highlighting working can sometimes be a little difficult. The stylesheet targets html classes produced by org to style them. But, for this to work, we have to tell org that we want it to export to html with these classes. To do so the following is required:

(setq org-html-htmlize-output-type 'css)

As far as I know there is no way to set this property locally in an org document. But if anyone knows a way I would love to know!
